<html>
<head>


<body>
<!-- We'll replace this content tag with whatever you write in your email  -->
<p class="unsubscribe">&nbsp;</p>
</body>
</html>


<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
</head>


<body >



<table>
    <tr>
        <td></td>
        <td rowspan=2><img src="http://paf.misevaluaciones.com/media/marcocumple.jpg"></td>
    </tr>
    <tr>
        <td colspan=2><div style="color:white;font-weight:bold;margin-left:100px;font-size:18px"> {{ nombre_completo }}</div></td>
    </tr>
</table>


</body>
</html>